spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: starrism-education-admin
          uri: lb://starrism-education-admin
          predicates:
            - Path=/se/v1/admin/**
          filters:
            - RewritePath=/se/v1(?<segment>/?.*), $\{segment}
        - id: starrism-education-auth
          uri: lb://starrism-education-auth
          predicates:
            - Path=/se/v1/auth/**
          filters:
            - RewritePath=/se/v1(?<segment>/?.*), $\{segment}
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
logging:
  level:
    nom.edu.starrism.gate: debug